### ISSUE TITLE
Request to add licence in the product

### ISSUE THREAD

**Issue by maheshwari-1153** [dvmjoshi/firebasecrud#1]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website. If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by dvmjoshi** [comment]
Hello,
sure you can add the repo .

**Comment by maheshwari-1153** [comment]
Hello, 
If you are interested showcase your products in our open source website then please add MIT Licence in your repo.

Thanks & Regards,
Maheshwari

**Comment by dvmjoshi** [comment]
> Hello,
> If you are interested showcase your products in our open source website then please

**Comment by dvmjoshi** [comment]
Mit licence added at the end of the repo.

**Comment by maheshwari-1153** [comment]
Thanks, this looks good. If it's fine with you can you please add licence file it would be lot more helpful.

**Comment by dvmjoshi** [comment]
added license  file
